name: Deploy Launch Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-2
  FRONTEND_INSTANCE_ID: i-04474421d6a28163d
  BACKEND_INSTANCE_ID: i-0a374e25291d206aa

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::597088015766:role/launch-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Create and deploy backend package
        run: |
          # Create deployment package with only necessary files
          zip -r deploy.zip \
            app.py \
            requirements.txt \
            gunicorn.conf.py \
            gunicorn.service \
            -x "*.git*" "*.github*" "frontend/*" "docs/*" ".cursor/*" "aws/*" "scripts/*" "iam/*"
          
          # Upload using AWS CLI and Session Manager
          aws s3 cp deploy.zip s3://launch-artifacts/backend-deploy.zip
          
          # Deploy using SSM
          aws ssm send-command \
            --instance-ids ${{ env.BACKEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "aws s3 cp s3://launch-artifacts/backend-deploy.zip /tmp/deploy.zip",
              "sudo mkdir -p /opt/launch/backend",
              "cd /opt/launch/backend",
              "sudo systemctl stop gunicorn || true",
              "sudo rm -rf /opt/launch/backend/*",
              "sudo unzip -o /tmp/deploy.zip -d /opt/launch/backend/",
              "sudo chown -R ubuntu:ubuntu /opt/launch/backend",
              "sudo python3 -m pip install --upgrade pip",
              "sudo python3 -m pip install -r /opt/launch/backend/requirements.txt",
              "sudo cp /opt/launch/backend/gunicorn.service /etc/systemd/system/gunicorn.service",
              "sudo systemctl daemon-reload",
              "sudo systemctl enable gunicorn",
              "sudo systemctl start gunicorn",
              "sleep 5",
              "sudo systemctl status gunicorn"
            ]'

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::597088015766:role/launch-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Build frontend
        run: |
          cd frontend
          # Create package.json with proper heredoc syntax
          cat > package.json << 'EOFMARKER'
          {
            "name": "launch-frontend",
            "version": "1.0.0",
            "scripts": {
              "build": "echo 'No build script defined'"
            }
          }
          EOFMARKER
          npm install --force
          npm run build

      - name: Deploy frontend
        run: |
          # Ensure dist directory exists
          mkdir -p frontend/dist
          
          # Create deployment package
          cp frontend/nginx/default.conf frontend/dist/
          cd frontend/dist
          zip -r ../../deploy.zip *
          cd ../..
          
          # Upload using AWS CLI and Session Manager
          aws s3 cp deploy.zip s3://launch-artifacts/frontend-deploy.zip
          
          # Deploy using SSM
          aws ssm send-command \
            --instance-ids ${{ env.FRONTEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "aws s3 cp s3://launch-artifacts/frontend-deploy.zip /tmp/deploy.zip",
              "sudo mkdir -p /opt/launch/frontend",
              "sudo rm -rf /opt/launch/frontend/*",
              "sudo unzip -o /tmp/deploy.zip -d /opt/launch/frontend/",
              "sudo cp /opt/launch/frontend/default.conf /etc/nginx/sites-available/default",
              "sudo rm -f /opt/launch/frontend/default.conf",
              "sudo chown -R ubuntu:ubuntu /opt/launch/frontend",
              "sudo nginx -t && sudo systemctl reload nginx || (sudo systemctl restart nginx && sleep 5)",
              "curl -s http://localhost/health || echo 'Health check failed'"
            ]' 