name: Deploy Launch Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-2
  FRONTEND_INSTANCE_ID: i-04474421d6a28163d
  BACKEND_INSTANCE_ID: i-0a374e25291d206aa

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::597088015766:role/launch-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest

      - name: Deploy to backend instance
        run: |
          # Create deployment package
          zip -r deploy.zip . -x "*.git*" "*.github*" "frontend/*"
          
          # Upload to instance
          aws ssm send-command \
            --instance-ids ${{ env.BACKEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "cd /opt/launch/backend",
              "sudo systemctl stop gunicorn",
              "sudo rm -rf /opt/launch/backend/*",
              "sudo unzip -o /tmp/deploy.zip -d /opt/launch/backend/",
              "sudo chown -R ubuntu:ubuntu /opt/launch/backend",
              "source /opt/launch/venv/bin/activate",
              "pip install -r requirements.txt",
              "sudo systemctl start gunicorn",
              "sudo systemctl status gunicorn"
            ]'

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::597088015766:role/launch-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to frontend instance
        run: |
          cd frontend
          
          # Create deployment package including nginx config
          cp nginx/default.conf build/
          zip -r deploy.zip build/
          
          # Upload to instance
          aws ssm send-command \
            --instance-ids ${{ env.FRONTEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "sudo rm -rf /opt/launch/frontend/*",
              "sudo unzip -o /tmp/deploy.zip -d /opt/launch/frontend/",
              "sudo cp /opt/launch/frontend/default.conf /etc/nginx/sites-available/default",
              "sudo chown -R ubuntu:ubuntu /opt/launch/frontend",
              "sudo nginx -t && sudo systemctl reload nginx"
            ]' 