name: Launch Application CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-2
  FRONTEND_INSTANCE_ID: i-04474421d6a28163d
  BACKEND_INSTANCE_ID: i-0a374e25291d206aa
  S3_BUCKET: launch-deployment

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend && pip install -r requirements.txt
        
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Run backend tests
        working-directory: ./backend
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd) python -m pytest tests/
        
      - name: Run frontend tests
        working-directory: ./frontend
        run: |
          echo "Running frontend tests..."
          npm run test -- --passWithNoTests # Temporarily allow no tests while we fix the structure

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::597088015766:role/launch-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Build and deploy frontend
        working-directory: ./frontend
        run: |
          # Install and build
          npm ci
          npm run build
          
          # Verify build output
          if [ ! -d "dist" ]; then
            echo "Build directory 'dist' not found!"
            exit 1
          fi
          
          # Upload to S3
          aws s3 cp dist s3://${{ env.S3_BUCKET }}/frontend/ --recursive
          
          # Deploy to EC2
          aws ssm send-command \
            --instance-ids ${{ env.FRONTEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "sudo mkdir -p /opt/launch/frontend",
              "sudo aws s3 sync s3://${{ env.S3_BUCKET }}/frontend/ /opt/launch/frontend/",
              "sudo chown -R ubuntu:ubuntu /opt/launch/frontend",
              "sudo systemctl reload nginx || sudo systemctl restart nginx",
              "curl -s http://localhost/health || exit 1"
            ]'

      - name: Build and deploy backend
        working-directory: ./backend
        run: |
          # Install dependencies
          pip install -r requirements.txt
          
          # Create deployment package
          zip -r deploy.zip . -x "*.git*" "*.github*"
          
          # Upload to S3
          aws s3 cp deploy.zip s3://${{ env.S3_BUCKET }}/backend/deploy.zip
          
          # Deploy to EC2
          aws ssm send-command \
            --instance-ids ${{ env.BACKEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "sudo mkdir -p /opt/launch/backend",
              "cd /opt/launch/backend",
              "sudo systemctl stop gunicorn || true",
              "sudo aws s3 cp s3://${{ env.S3_BUCKET }}/backend/deploy.zip /tmp/deploy.zip",
              "sudo unzip -o /tmp/deploy.zip -d /opt/launch/backend/",
              "sudo chown -R ubuntu:ubuntu /opt/launch/backend",
              "python3 -m venv /opt/launch/venv",
              "source /opt/launch/venv/bin/activate",
              "pip install -r requirements.txt",
              "sudo systemctl restart gunicorn",
              "sleep 5",
              "curl -s http://localhost:8000/health || exit 1"
            ]' 