name: Test Database Connection

on:
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2
          
      - name: Test database connection
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.BACKEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "cd /opt/launch/backend",
              "source venv/bin/activate",
              "pip install -r requirements.txt",
              "DB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id /launch/db/credentials --query SecretString --output text | jq -r .password)",
              "python scripts/test_db_connection.py"
            ]' 